# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: alexandrosnt.Reach
PackageVersion: 0.7.4
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-10-02
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/alexandrosnt/Reach/releases/download/v0.7.4/Reach_0.7.4_x64-setup.exe
  InstallerSha256: D0327FD9CE215E3C12E2D022877DD473931B53386B74CE5BED31260E644747BF
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/alexandrosnt/Reach/releases/download/v0.7.4/Reach_0.7.4_x64-setup.exe
  InstallerSha256: D0327FD9CE215E3C12E2D022877DD473931B53386B74CE5BED31260E644747BF
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/alexandrosnt/Reach/releases/download/v0.7.4/Reach_0.7.4_x64_en-US.msi
  InstallerSha256: 682E2E544471C70B8ED93D9C8C7293D370B2594B58BBB4FE69BAFDC270A351AD
  ProductCode: '{34F9ABFA-7C64-4644-B57B-66FBF3F4AF0F}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1100BA3D-2CD3-5FD2-9DAD-903D23E8C53B}'
ManifestType: installer
ManifestVersion: 1.12.0
