# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: alexandrosnt.Reach
PackageVersion: 0.6.8
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-09-25
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/alexandrosnt/Reach/releases/download/v0.6.8/Reach_0.6.8_x64-setup.exe
  InstallerSha256: B51B83A58F6A66CD9CFCB81E690541348ACC4A96CB15DF202B76D7C1D4745110
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  InstallerType: nullsoft
  Scope: machine
  InstallerUrl: https://github.com/alexandrosnt/Reach/releases/download/v0.6.8/Reach_0.6.8_x64-setup.exe
  InstallerSha256: B51B83A58F6A66CD9CFCB81E690541348ACC4A96CB15DF202B76D7C1D4745110
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/alexandrosnt/Reach/releases/download/v0.6.8/Reach_0.6.8_x64_en-US.msi
  InstallerSha256: D1BCF66FFF87542B0BCAA02A4FC2BE70DC492FB261DFD73986D77E42646C56A0
  ProductCode: '{0F91A2B5-163D-42BB-AAC7-D32415B7E333}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{1100BA3D-2CD3-5FD2-9DAD-903D23E8C53B}'
ManifestType: installer
ManifestVersion: 1.12.0
